### ISSUE TITLE
The question of dataset 

### ISSUE THREAD

**Issue by yanfeihong** [vanAmsterdam/lidc-binary-classification#1]
Hello, thank you very much for your project on LIDC binary-classification. However, I have a question, how do you get the image in ".png" format? The original format of the LIDC-IDRI dataset is ".dcm"? Looking forward to your reply, thank you

**Comment by yanfeihong** [comment]
Hello, thank you very much for your project on LIDC binary-classification. However, I have a question, how do you get the image in ".png" format? The original format of the LIDC-IDRI dataset is ".dcm"? Looking forward to your reply, thank you

**Comment by vanAmsterdam** [comment]
Hi yanfeihong, please follow the README for installing the right python modules. Afterwards, following the steps in 'lidc-preprocessing.ipynb' should give you 2 things: a folder with numpy arrays of the tumor volumes (remember, a scan is 3D so you cannot save an entire scan in png), and a folder with images of slices of the tumors, these are in .png

**Comment by yanfeihong** [comment]
thinks, I did it！
