### ISSUE TITLE
Usage error: line magic function '%cp' not found

### ISSUE THREAD

**Issue by aolakunleabayomi** [vanAmsterdam/lidc-binary-classification#3]
Hello,

Running this cell of codes in lidc-preprocessing.ipynb:

In [75]:
for i, file in enumerate(malignant_filenames):
    in_path  = os.path.join(npy_dir, file)
    out_path = os.path.join(sorted_dir, "malignant", str(malignant_idx[i])+".npy")
    %cp $in_path $out_path

I keep getting the error: Usage error: line magic function '%cp' not found.

Please can u help me?

**Comment by vanAmsterdam** [comment]
Hi, what platform are you running this on, windows? cp is a command on linux and mac systems for copying

a better approach would be to add:

```python
import shutil
```

to the imports

and replace the line with `%cp` to:

```python
shutil.copy(in_path, out_path)
```

**Comment by vanAmsterdam** [comment]
i've fixed it in the newest commit; does this work?

**Comment by aolakunleabayomi** [comment]
Thanks. It worked
